# Doctr requires python >=3.5
language: python
python:
  - 3.6

# This gives Doctr the key we've generated
sudo: false
install:
  - pip install -r requirements.txt

# This is the script to build the docs on travis, then deploy
script:
  - set -e
  - pip install doctr
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs docs/_build/html

env:
  global:
    # Doctr deploy key for pauleveritt/visual_testing
    - secure: "T1KEdSjjgfPENPRH/hP9/p3EheaGHDJJtMLuQMwcN5TczgDZGD+6YLQEV/CcEuEzbxzcMb3WgOiVlYFMcJbBZx3s7Mkq5rCJtpdvWgDg8Q8f1fTd96ks7Bb8qJyPTDT0yxRKHfjdw80P/AEv5nad86oa/va+1q76kBY0beKwYz3driWzi5vdtnAQmzzc7HEPz1pZ1Aa0IG4GXmDSwu9j5NqueY7y/T4BujqsWTOnLSHAjon5YpiHnm12JoCzhN1rnjyxWOIeSDjFmnplsUjCaWw8y0iEvkUmZ+5alUhQUNL7vVWiydtUYH74Jv1R7d7ktjmqEYVikXesBl8KOp5cPNxvEmrysysN8LIXHZJh/HJm7olYLBOxfcSdc71uN+aFjDAZyWRoHciv9ZLBHrvAtzT4HT5TYzTOadKXOMHMoS8M7LuVjd1y9lulPocJyKPZEsf2A8xieeibom7K6AvUULFylbJKkEIqOWoWUzGcXDrfEkidW/C0QeA5j+Jxd6VuNBFh+DMD93D74XEedet7fZ+C45mpv+8qlxsciysNgWfZsBCSMqMSZ+VFuPsaDez7JvY2NMhO9hL/m07/nMRSdcyyLoBHEO57jI32rSrCLfbbwVsvWmHbOiG3A5QMLB+uj3rLY5LCTz4jlQNj4XP7Avf4KMcwVQBuhoAlaCNusV4="

