# Doctr requires python >=3.5
language: python
python:
  - 3.6

# This gives Doctr the key we've generated
sudo: false
install:
  - pip install -r requirements.txt

# This is the script to build the docs on travis, then deploy
script:
  - set -e
  - pip install doctr
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs docs/_build/html

env:
  global:
    # Doctr deploy key for pauleveritt/visual_testing

